name: Build and Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Container Registry
        run: |
          echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u marke16 --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile.prod -t ghcr.io/marke16/livecanvas:prod .
          docker push ghcr.io/marke16/livecanvas:prod

      - name: Deploy to Render
      - run: |
          curl -X POST \
          --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
          --header 'accept: application/json' \
          --header 'content-type: application/json' \
          --header 'authorization: Bearer ${{ secrets.RENDER_KEY }}' \
          --data '{
          "commitId": "${{ github.sha }}",
          "imageUrl": "ghcr.io/marke16/livecanvas:prod"
          }'
