name: Syncronize With LiveCanvas

on:
  schedule:
    # Sync every Thursday at midnight.
    # Note: syntax for cron is "minute hour day month day-of-week"
    # where * means any value. For example, * * * * * means every minute of every hour of every day of every month of every day of the week.
    - cron: "0 0 * * 4"
  workflow_dispatch: # Allows the workflow to be run manually

jobs:
  syncronize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SYNC_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USERNAME }}

      - name: Add Remote
        run: git remote add upstream https://github.com/MarkE16/LiveCanvas.git

      - name: Syncronize
        run: |
          git fetch upstream # Fetch the upstream main branch
          git checkout main # Checkout the main branch
          git merge upstream/main --allow-unrelated-histories # Merge the upstream main branch into the main branch. Allow unrelated histories to be merged

          rm .github/workflows/deploy.yml # Remove the deploy.yml file. This workflow is to deploy to Vercel; we are not deploying to Vercel in this repository.

          git add . # Add all the changes
          git commit -m "sync workflow" # Commit the changes
          git push origin main # Push the changes to the main branch
